version: "3"

services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: 4gb
    ports:
      - "4444:4444"
      - "7900:7900"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'